version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: prayer_time
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - spring-net

  app:
    build: .
    container_name: prayer-time-app
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prayer_time
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypassword
      CLOUD_AWS_S3_ENDPOINT: http://minio:9000
      CLOUD_AWS_REGION: us-east-1
      CLOUD_AWS_ACCESSKEY: minioadmin
      CLOUD_AWS_SECRETKEY: minioadmin
      CLOUD_AWS_PATH_STYLE_ACCESS: true
    ports:
      - "8080:8080"
    networks:
      - spring-net

volumes:
  postgres_data:
  minio_data:

networks:
  spring-net:
