# Datasource
spring.application.name=prayertime
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prayer_time}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mypassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Object Storage
cloud.aws.s3.endpoint=${CLOUD_AWS_S3_ENDPOINT:http://localhost:9000}
cloud.aws.region=${CLOUD_AWS_REGION:us-east-1}
cloud.aws.accessKey=${CLOUD_AWS_ACCESSKEY:minioadmin}
cloud.aws.secretKey=${CLOUD_AWS_SECRETKEY:minioadmin}
cloud.aws.path-style-access=${CLOUD_AWS_PATH_STYLE_ACCESS:true}
